services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  Tourze\JsonRPCTurboBundle\Service\:
    resource: '../../Service/'

  Tourze\JsonRPCTurboBundle\Service\MethodResolver: ~  # 确保这个类是服务
  Tourze\JsonRPC\Core\Domain\JsonRpcMethodResolverInterface:
    alias: Tourze\JsonRPCTurboBundle\Service\MethodResolver
    public: true
